services:

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/access.log:/var/log/nginx/access.log
      # - static_volume:/usr/src/app/static
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "80:80"

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    container_name: app
    build:
      context: .
      target: development
    depends_on:
      - db
    volumes:
      - .:/app/
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
