# Generated by Django 4.0.4 on 2022-05-30 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
